# Generated by Django 3.2.6 on 2022-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('birth_date', models.DateField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('TUTOR', 'Куратор'), ('TEACHER', 'Вчитель'), ('STUDENT', 'Учень'), ('HEADTEACHER', 'Директор')], max_length=20)),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
    ]
